apiVersion: v1
kind: Service
metadata: 
    name: t2s-cluster-nodeport
spec:
    type: NodePort
    selector:
        component: t2s-backend
    ports:
        - port: 8000
          targetPort: 8000
