apiVersion: v1
kind: Service
metadata: 
    name: sentiment-cluster-nodeport
spec:
    type: NodePort
    selector:
        component: sentiment-backend
    ports:
        - port: 8000
          targetPort: 8000
